# run settings
delay: 2                          # Delay between execution cycles (in seconds)

# exchange settings
exchange: binance                 # Exchange (currently only binance is supported)
market_type: PERPETUAL            # Market type (currently only PERPETUAL is supported)
symbol: XRPUSDT                   # Trading pair symbol
sell_interval: 1d                 # Candle interval for sell (e.g., 1m, 5m, 15m, 1h)
buy_interval: 1m                      # Candle interval (e.g., 1m, 5m, 15m, 1h)
candles_limit: 2                  # Number of candles to fetch


# trade settings
START_AMOUNT: 0.2                 # USDT
SELL_ON_PERCENT_CHANGE: 3       # % каждые сколько процентов продавать
SELL_PERCENT_ON_CANDLE_ENDS: 100  # % сколько процентов всего продать?
