symbol: XRPUSDT           # Trading pair symbol
interval: 1m              # Candle interval (e.g., 1m, 5m, 15m, 1h)
market_type: PERPETUAL    # Market type (currently only PERPETUAL is supported)
exchange: binance         # Exchange (currently only binance is supported)
candles_limit: 2          # Number of candles to fetch
delay: 2                  # Delay between execution cycles (in seconds)
